### ISSUE TITLE
fetching kills since 14.08

### ISSUE THREAD

**Issue by infinity223** [evekb/evedev-kb#110]
I got this error since 14.08

[404] Error connecting to the API (https://esi.evetech.net/v3/universe/names/?datasource=tranquility)

Cant fetch kills.

But strangely, I have 8 sso accounts added, for 6 I cant fetch kills (inc two corps) and for 2 others I can :D

**Comment by Salvoxia** [comment]
Hi,

this is caused by [this ESI issue](https://github.com/esi/esi-issues/issues/1134) with the universe/names ESI endpoint.
CCP devs said we could expect a fix on Monday.
As soon as the endpoint is fixed, posting kills should be possible again.

Regarding your SSO accounts: Do the two working ones actually have new kills to post? Or are these the only ones with no new kills? 

Best Regards,
Salvoxia

**Comment by infinity223** [comment]
"Or are these the only ones with no new kills" prob no new kills, bcs not so active accounts.

So we are waiting for a fix, thanks for info!

**Comment by infinity223** [comment]
working right now after fix.
