### ISSUE TITLE
issue after aegis update

### ISSUE THREAD

**Issue by azak1r** [evekb/evedev-kb#43]
hey guys, i just ran the auto update for the aegis release. 
did this through the admin panel and shortly after the installation i got redirected to 
https://https/lone-star-warriors.com/killboard/update/

everytime i try access the killboard i get the same redirect and it is simply in accessible.
any idea on how to fix this? would appreciate it

The killboard is located at https://lone-star-warriors.com/killboard

**Comment by hglock** [comment]
When clicking your link, I get redirected to:
https://https/lone-star-warriors.com/killboard/update/

There is one "https/" too much in this URL. Can you try to fix the URL manually, so call
https://lone-star-warriors.com/killboard/update/
instead of
https://https/lone-star-warriors.com/killboard/update/

**Comment by azak1r** [comment]
Oww yeah I see it now, this has fixed the issue. Thanks for the help. Ticket closed
