### ISSUE TITLE
zkillboard or crest import error with skin

### ISSUE THREAD

**Issue by MourningWood** [evekb/evedev-kb#55]
While trying to post a kill that has a skin in the items I get the following error:

Fatal error: Call to a member function getName() on boolean in /path/killboard/common/includes/class.kill.php on line 1405

link to kill
https://zkillboard.com/kill/52756014/

**Comment by Salvoxia** [comment]
Hi,

thanks for reporting and your analysis! This commit will fix that problem: 899b13acd5393e0280247ce590c8a1ef37d591a0

Best Regards,
Salvoxia

**Comment by MourningWood** [comment]
Thank you for the quick reply.  I should have mentioned that I had verified that change was applied before submitting the error.  I just tried to post the kill again and got the same error.  I did a little trouble shooting first confirming the SKIN was in the database and then printed the destroyed items array out, it has all the items except for the SKIN.  I then had it print out each item name until it broke so I could see exactly where its breaking.  The next array object is empty so I'm guessing it would be the skin.  I've also tried importing the kill via crest instead of zkillboard import.

[17] => DestroyedItem Object
        (
            [item_] => 
            [quantity_] => 1
            [location_] => 
            [locationID_] => 5
            [value:DestroyedItem:private] => 
            [singleton_:DestroyedItem:private] => 0
        )

**Comment by Salvoxia** [comment]
Hi,

I tried reproducing the problem on my development board. Without the linked hotfix I got the error. With it, it posted fine.
I tried posting it via the CREST link itself as well as fetching it from zKillboard. I tried various cache settings and looked through the code if caching could be an issue. I found piece of code that might run into caching issues, I was not able to provoke them, though. (I removed the SKIN from the database and cleared any caches between each try.)
If you can rule out caching as a possible cause, would you be willing to share a link to your killboard so that I can play around a bit?

Best Regards,
Salvoxia

**Comment by MourningWood** [comment]
I just realized I read the hotfix backwards.  Thank you for your help.
