### ISSUE TITLE
Banner resize

### ISSUE THREAD

**Issue by KongGal** [evekb/evedev-kb#78]
I tried putting a corporation logo as banner which left the killboard with a little picture on the left side of the banner area when i then made a banner with the size of the default one 950x125 px it would then just put it into that little box it made for the corporation logo instead of showing it in full size 

https://rr.tluc.me  and this is the banner https://rr.tluc.me/banner/rr-notext.png
  
i tried clearing caches and such but with no luck

**Comment by Salvoxia** [comment]
Hi,

when changing the banner to 950x125, did you simply replace the image file in the banners folder?
The killboard calculates the size of the banner file when you change the banner in the admin control panel. So if you did change the banner size afterwards, you'll have to switch to another banner and back again, so that the correct image size will be calculated and store in the configuration.
Currently, it seems to think the is 128x128px, which might be right for a sole corp logo.

Best Regards,
Salvoxia

**Comment by KongGal** [comment]
First i took the 128px corp logo from CCP's image server, saved it and dumped it into the banner folder
it then made the little 128x128 field which it shows the banners in now, but when i try to change to another banner it just stay the same size

I added new files to the folder called banner and switched to it in the admin panel
http://prntscr.com/f0xtqv

Found the strings in the database and fixed it by hand not sure what messed up the calculation :/

Also now that i have you Salvoxia any idea why the EDK killboard would skip an entire day of killmails fetched from zkb?

**Comment by Salvoxia** [comment]
Kills should only be skipped if either there is an error parsing/posting or the kill already exists at your killboard. The latter is the usual case, zKBFetch with default settings will regularly skip kills.
If there's an error parsing/posting, the error message should be part of the cronjob output.

Skipping a full day is certainly not usual, but if there are no errors, the kills should already exist.

Best Regards,
Salvoxia

**Comment by Salvoxia** [comment]
I'm assuming this is resolved, closed.
