### ISSUE TITLE
Zkillboard Issue

### ISSUE THREAD

**Issue by CokkocZateki** [evekb/evedev-kb#79]
Hi.

I tried to do a fetch from zkillboard and my site gave me an error 500 when i clicked on fetch.

logging in the logs i got the following error. anyone know or seem this issue before

`PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/killboard/common/includes/class.simplecrest.php:84\nStack trace:\n#0 /var/www/killboard/common/includes/class.simplecrest.php(58): SimpleCrest::getCrestByCurl('https://zkillbo...')\n#1 /var/www/killboard/common/includes/class.zkbfetch.php(302): SimpleCrest::getReferenceByUrl('https://zkillbo...')\n#2 /var/www/killboard/common/includes/class.zkbfetch.php(393): ZKBFetch->fetch()\n#3 /var/www/killboard/common/admin/admin_zkbfetch.php(180): ZKBFetch->processApi()\n#4 /var/www/killboard/common/admin/admin_zkbfetch.php(124): getZKBApi(Object(ZKBFetch))\n#5 /var/www/killboard/common/index.php(323): include('/var/www/killbo...')\n#6 /var/www/killboard/index.php(25): include('/var/www/killbo...')\n#7 {main}\n  thrown in /var/www/killboard/common/includes/class.simplecrest.php on line 84, referer: http://xxxxx/killboard/?a=admin_zkbfetch`

**Comment by Salvoxia** [comment]
Hi,

PHP complains it does not know about a function curl_init(), meaning it does not have the cURL support.
Since EDK tries to determine whether cURL is available or not, and then chooses the best setting for doing HTTP calls, that either means that you did once use a PHP version with cURL support, or you manuall changed the setting from "file" to "cURL" (in ACP -> Configuration -> API connection method). 
ACP -> Troubleshooting should give a better overview.

Is it possible you are not using the same PHP version you did before? I strongly advise to make sure cURL is available, since future EDK versions will require it.

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
ahhhh duuuhhh. curl was missing. i upgraded to php 7.0 and forgot about curl. problem solved.
