### ISSUE TITLE
Resolving Corporations fails with 400

### ISSUE THREAD

**Issue by Fundaris** [evekb/evedev-kb#88]
Hey after some weird duplicate pilot things I saw this in /cron/cron_esi.php

https://esi.evetech.net/v2/corporations/names/?corporation_ids=<long list of ids>

`{"error":"too many items for 'corporation_ids', 'corporation_ids' is required"}`

**Comment by Salvoxia** [comment]
Hi,

that problemw as fixed with this commit: https://github.com/evekb/evedev-kb/commit/db935e88db34ff1a9e78963bd6fed94fca8f6bb2#diff-9980fcde3560636f88e8d3d11ad8bf3d

But what do you mean with duplicate pilots?

**Comment by Fundaris** [comment]
Duno if it works https://media.discordapp.net/attachments/332942510315929603/454349208313397251/unknown.png

**Comment by Salvoxia** [comment]
That's a real ancient database you got there.
I don't really have en explanation for what's happening there, other than the first character no longer exists and the last time it was updated was before API killmails existed.
One possibility would be that that character's name was changed, which doesn't handle EDK very well, due to its history.
I suggest to manually remove the external ID from the first character and clear your cache afterwards.

Best Regards,
Salvoxia

**Comment by Fundaris** [comment]
> One possibility would be that that character's name was changed, which doesn't handle EDK very well, due to its history.

I would go with this :) and thx for the help ported some fixes and kb seems to be getting seeded again
