### ISSUE TITLE
"Unknown solar system ID" when parsing kills with ESI

### ISSUE THREAD

**Issue by georgekaf** [evekb/evedev-kb#91]
Unknown solar system ID: 32000029, KillID = 70280958
Unknown solar system ID: 32000029, KillID = 70280989
Unknown solar system ID: 32000014, KillID = 70645671
Unknown solar system ID: 32000014, KillID = 70645698
Unknown solar system ID: 32000048, KillID = 70667993
Unknown solar system ID: 32000048, KillID = 70668023

**Comment by Salvoxia** [comment]
Hi,

this is related to Abyssal Deadspace.
These new solar systems need to be in EDK's database so that kills can be posted.

An EDK update is scheduled for next weekend.
As an alternative you can manually update the database using [this standalone package](http://www.evekb.org/downloads/edk_intotheabyss_1.0.20180529.zip).

Best Regards,
Salvoxia

**Comment by georgekaf** [comment]
Thank you. I have already imported it though.
Systems with IDs 32000014 and 32000029 seems they are missing from kb3_mapdenormalize.sql.

`
george@host:~/Downloads/edk_intotheabyss_1.0.20180529/multiple$ grep -rn "32000048"
kb3_mapdenormalize.sql:238496:	(40238617, 14, 8, 30003765, 20000549, 10000047, 40238615, -535985847526, 89320000488, -153443767811, 440000, 'IWZ3-C VIII - Moon 1', -0.0854189760543497, 8, 1),
kb3_systems.sql:8114:	(32000048, 22000006, '32000048', 4.64109e18, 4.45065e18, 5.42787e18, -0.99000),`

`
george@host:~/Downloads/edk_intotheabyss_1.0.20180529/multiple$ grep -rn "32000014"
kb3_systems.sql:8080:	(32000014, 22000002, '32000014', 3.34779e18, 5.07576e18, 5.43076e18, -0.99000),
`

`george@host:~/Downloads/edk_intotheabyss_1.0.20180529/multiple$ grep -rn 32000029
kb3_systems.sql:8095:	(32000029, 22000004, '32000029', 3.17157e18, 4.94764e18, 5.59077e18, -0.99000),
`

**Comment by Salvoxia** [comment]
Hi, 

I checked and found that these systems do not have entries in Steve's conversion as well.
I think that is correct, since this table lists static celestials in solar systems. And Abyssal Deadspace systems don't seem to have any celestials, not even suns.
EDK does not require entries in this table to handle such kills. There simply won't be a nearest celestial listed for any losses in these systems.

Best Regards,
Salvoxia

**Comment by georgekaf** [comment]
Thank you. This can close then
